workspace:
  base: /go/src
  path: github.com/kradalby/bork

pipeline:
  lint:
    image: golang:latest
    commands:
          - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          - golangci-lint --version
          - golangci-lint run

  lint-frontend:
    image: node:10
    commands:
        - cd frontend
        - yarn
        - npx elm-analyse
        - npx stylelint src/*.scss

  build:
    image: plugins/docker
    repo: kradalby/bork
    # auto_tag: true
    secrets: [ docker_username, docker_password ]
    tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest

  deploy:
     image: quay.io/honestbee/drone-kubernetes
     deployment: bork-deployment
     repo: kradalby/bork
     container: bork-container
     namespace: bork
     secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
     tag:
       - ${DRONE_COMMIT_SHA:0:8}

  notify:
    image: drillster/drone-email
    host: smtp.fap.no
    skip_verify: true
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
